[project]
name = "ai-knowledge-assistant"
version = "0.1.0"
description = "I try to build ai-knowledge-assistant"
readme = "README.md"
authors = [
    { name = "Naowal Siripatana", email = "naowalzaza@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.mypy]
python_version = "3.11"
files = "src"
ignore_missing_imports = true
check_untyped_defs = true
warn_unused_ignores = true
